## Server properties
server:
  port: 5000
## Spring datasource (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    # The SQL driver class name using the MySQL Connector/J JDBC driver for connecting to a MySQL database
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/topic-talks?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: p4ssw0rd!
## Hibernate properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
## Configuration validation
  messages:
    basename: messages
## Configuration jwt
application:
  security:
    jwt:
      secret-key: TopicTalkSecretKey!@$%#^&*()
      expiration: 900000 #  15 min in ms
      refresh-token:
        expiration: 1296000000 # 15 days in ms
## Configuration twilio
twilio:
  account:
    sid: ACe74e66f851d87f7ce4b8b9e9535862a9
  auth:
    token: 50373b7b61f3de511c340c5542632173